package br.com.java_brasil.boleto.service.bancos.bradesco_api.model;

import lombok.Getter;
import lombok.Setter;

import java.io.InputStream;

@Getter
@Setter
public class BoletoBradescoAPIResponse {

    private String bairroBeneficiario;
    private String bairroPagador;
    private String cdBarras;
    private Integer cdJuros;
    private Integer cdValorDesconto1Bonificacao;
    private Integer cdValorDesconto2;
    private Integer cdValorDesconto3;
    private Integer cdValorJuros;
    private Integer cdValorMulta;
    private Integer cepBeneficiario;
    private Integer cepComplementoBeneficiario;
    private String cepComplementoPagador;
    private Integer cepComplementoSacadorAvalista;
    private Integer cepPagador;
    private Integer cepSacadorAvalista;
    private Long cnpjCpfSacadorAvalista;
    private String codigoMoedaTitulo;
    private Integer codigoOrigemProtesto;
    private String codigoOrigemTitulo;
    private String codigoRetorno;
    private String complementoLogradouroBeneficiario;
    private String cpfcnpjBeneficiario;
    private Long cpfcnpjPagador;
    private String dataEnvioCartorio;
    private String dataPedidoSustacao;
    private String dataSustacao;
    private String descCdDesconto1Bonificacao;
    private String descCdDesconto2;
    private String descCdDesconto3;
    private String descCdMulta;
    private String descEspecie;
    private String descricacaoMoeda;
    private Integer diasDispensaJuros;
    private Integer diasDispensaMulta;
    private Integer diasInstrucaoProtestoNegativao;
    private Integer diasJuros;
    private String dtDesconto1Bonificacao;
    private String dtDesconto2;
    private String dtDesconto3;
    private String dtEmissao;
    private String dtInstrucaoProtestoNegativao;
    private String dtJuros;
    private String dtLimitePagamentoBoleto;
    private String dtMulta;
    private String dtRegistro;
    private String dtVencimento;
    private String dtVencimentoBoleto;
    private String endEletronicoPagador;
    private String enderecoPagador;
    private String enderecoSacadorAvalista;
    private String especieDocumentoTitulo;
    private Integer idProduto;
    private Integer indInstrucaoProtesto;
    private String linhaDigitavel;
    private String logradouroBeneficiario;
    private String mensagemRetorno;
    private String municipioBeneficiario;
    private String municipioPagador;
    private String municipioSacadorAvalista;
    private Long negociacao;
    private String nomeBeneficiario;
    private String nomePagador;
    private String nomeSacadorAvalista;
    private String nuControleParticipante;
    private String nuLogradouroBeneficiario;
    private Long nuTituloGerado;
    private String numeroCartorio;
    private String numeroProtocoloCartorio;
    private Integer qtdeCasasDecimaisDesconto1Bonificacao;
    private Integer qtdeCasasDecimaisDesconto2;
    private Integer qtdeCasasDecimaisDesconto3;
    private Integer qtdeCasasDecimaisMulta;
    private Integer quantidadeCasas;
    private Long quantidadeMoeda;
    private String seuNumeroTitulo;
    private String tipoEndosso;
    private Integer tpDesconto1;
    private Integer tpDesconto2;
    private Integer tpDesconto3;
    private Integer tpVencimento;
    private String ufBeneficiario;
    private String ufPagador;
    private String ufSacadorAvalista;
    private Long valorDespesas;
    private Long vlAbatimento;
    private Long vlDesconto1Bonificacao;
    private Long vlDesconto2;
    private Long vlDesconto3;
    private Long vlIOF;
    private Long vlJuros;
    private Long vlJurosAoDia;
    private Long vlMulta;
    private Long vlTitulo;
    private Long vlTituloEmitidoBoleto;
    private String enderecoBeneficiarioCompleto;
    private String agenciaECodigoBeneficiario;
    private String fatura;
    private String localDePagamento;
    private String instrucoes;
    private String carteira;
    private InputStream logotipo;
    private InputStream logotipo2;
    private String nossoNumero;
    private String digitoNossoNumero;
    private String nossoNumeroECodDocumento;
    private String cepCompletoPagador;
}

